### ISSUE TITLE
出力するエントリー数を指定できるように。

### ISSUE THREAD

**Issue by pooza** [pooza/toot-feed#10]

**Comment by pooza** [comment]
URLのクエリーから設定することは当然可能だが、極端に大きな数字を入れてDoS攻撃まがいのこともできてしまう。
local.yamlに最大値を記述する様にして、管理者がサーバのスペックや用途に合わせた設定を行える様にするのが無難か。

**Comment by pooza** [comment]
```
root_url: https://mstdn.b-shock.org/
tz_offset: 9
entries:
  max: 200
  default: 20
```
こんな感じの記述を想定。
IFTTTの定期巡回が15分周期であることを踏まえ、maxを調整する。
